apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      node-app: web
  template:
    metadata:
      labels:
        node-app: web
    spec:
      containers:
        - name: my-app
          image: nodatabase/my-app:lab3
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-node-app-service
  namespace: default
spec:
  type: NodePort
  selector:
    node-app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001