name: Devops CICD

on:
  push:
    branches: ["main", "test"]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code from the repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 12
      - run: npm ci

      - name: Lint the code with ESLint
        run: npm run lint

  build-and-push:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out code from the repository
        uses: actions/checkout@v3

      - name: Build and push docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: nodatabase/my-app-new
          registry: docker.io
          addLatest: true
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}